apiVersion: v1
kind: Pod
metadata:
  name: sample-env-container
  labels:
     app: sample-app
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    env:
    - name: MAX_CONNECTION
      value: "100"
    - name: K8S_NODE
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: CPU_REQUESTS
      valueFrom:
        resourceFieldRef:
          containerName: nginx-container
          resource: requests.cpu